feat. add Deu i18n language support
retrofor/iamai pull request #303
Opened 2024-11-10 18:18 UTC by BegoniaHe

Das ist die deuchte Sprachehilfspackung für iamai. Alle Übersetzung wird doublechecked von Begonia.

2024-11-10 18:26 UTC, BegoniaHe commented
Entschuldigung, aber ich hab eine Frage, wie kann die i18n Files zu docs übersetzet werden? Ich habe einmal versucht, dass ich in dem Terminal `maturin build` eingab. Aber nichts passiert, und die Deutsch Übersetzung kommt nicht auf.

2024-11-11 00:04 UTC, HsiangNianian requested changes
Add .DS_Store in the .gitignore file

2024-11-11 02:26 UTC, HsiangNianian commented
Thanks for your contribution to iamai i18n component, and, please make sure you have complete all the changes requested, once you fixed it you can reply this message and I'll review PR again :D

2024-11-11 10:28 UTC, BegoniaHe commented
Entschuldigung und dürfte ich eine Frage stellen, wie kann ich das Problem mit sogenannte `License Compliance` handeln? Die Warnung in dem Request kommt immer auf...
<img width="923" alt="截屏2024-11-11 11 26 10" src="https://github.com/user-attachments/assets/f3648301-0d3d-4a8c-8afc-e7d56b2b8d56">
Vielen dank für die Überprüfung und wünsche dir einen schönen Tag!

2024-11-11 13:28 UTC, merged